### ISSUE TITLE
师傅，windows环境运行的好像有问题

### ISSUE THREAD

**Issue by dragon-fox** [novysodope/yonyou_check#3]

**Comment by novysodope** [comment]
啥问题，有具体报错或截图吗

**Comment by mylaracroft** [comment]
[0m                                                                                                                                            
[[33mINFO[0m] http://192.168.1.222:8888                                                                                                       
[[36m14:08:50[0m] [[33m-[0m] 不存在用友 sync反序列化漏洞                                                                                               
panic: runtime error: invalid memory address or nil pointer dereference                                                                         
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x2caf07]                                                                                              
                                                                                                                                                
goroutine 1 [running]:                                                                                                                          
FoPoForYonyou2.0/Scan.GetSessionListScan({0xc00009a060, 0x19}, 0x30?, {0x5408e0?, 0x34a624?}, {0x34a624, 0x5}, {0x34a629, 0x5}, {0x34a3b9, ...},
 ...)                                                                                                                                           
        E:/1-gostudy/FoPoForYonyou2.0/Scan/GetSessionListModule.go:16 +0xa7                                                                     
FoPoForYonyou2.0/Distribute.ModuleConf({0xc00009a060, 0x19}, 0xc0000c1ce8?, {0x34a61f, 0x5}, {0x34a624, 0x5}, {0x34a629, 0x5}, {0x34a3b9, ...}, 
...)                                                                                                                                            
        E:/1-gostudy/FoPoForYonyou2.0/Distribute/Configuration.go:12 +0x1ab                                                                     
main.TargetParse({0xc00009a060, 0x19}, {0x0?, 0xc00003fdd8?}, {0x34a61f, 0x5}, {0x34a624, 0x5}, {0x34a629, 0x5}, ...)                           
        E:/1-gostudy/FoPoForYonyou2.0/Parser.go:38 +0x2a5                                                                                       
main.main()                                                                                                                                     
        E:/1-gostudy/FoPoForYonyou2.0/main.go:89 +0x4e5
